In [1]:
# Importing libraries

import numpy as np
import pandas as pd

Reading .csv file

In [50]:
df = pd.read_csv("data/Clientes.csv", delimiter =',' )
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22

Looking for "Mato Grosso" in the 'state' column

In [48]:
mt_state = df.loc[df['state'] == 'Mato Grosso']
mt_state

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não registrado,0,Sem complemento
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1,Conjunto 23
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,Não registrado,0,Conjunto 4
66,66,2018-10-18 04:31:59,Stephanie,Abreu,stephanie@meu_email.com,9 6466-2389,Brasil,Mato Grosso,Rua 19 do Estado Mato Grosso,53,Conjunto 13
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24,Sem complemento

Looking for a list of states

In [44]:
states = ['Mato Grosso','Bahia', 'São Paulo']

df_states = df.loc[df['state'].isin(states)]
df_states

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,NaN,NaN,Conjunto 4
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
32,32,2018-07-22 11:59:27,Ana,Campos,ana@teste.com,9 1932-9841,Brasil,Bahia,Avenida 52 do Estado Bahia,402.0,NaN
58,58,2018-09-13 03:13:02,Rafael,Rodrigues,rafael@meu_email.com,9 6550-3557,Brasil,Bahia,Praça 94 do Estado Bahia,647.0,Apto 25
59,59,2017-12-03 16:24:32,Stephanie,Freire,stephanie@usuario.com,9 3256-1853,Brasil,São Paulo,Rua 52 do Estado São Paulo,34.0,Apto 24
66,66,2018-10-18 04:31:59,Stephanie,Abreu,stephanie@meu_email.com,9 6466-2389,Brasil,Mato Grosso,Rua 19 do Estado Mato Grosso,53.0,Conjunto 13
77,77,2018-11-30 10:29:55,Ana,Monteiro,ana@teste.com,9 3871-4132,Brasil,Bahia,Praça 86 do Estado Bahia,604.0,Apto 30
78,78,2017-11-02 22:13:22,Laura,Queiroz,laura@exemplo.com,9 6338-8617,Brasil,São Paulo,Praça 19 do Estado São Paulo,878.0,Conjunto 3
89,89,2017-12-07 19:24:54,Daniela,Pires,daniela@usuario.com,9 6666-2265,Brasil,Bahia,Rua 31 do Estado Bahia,441.0,NaN
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN

Handling NaNs and nulls in the 'street' and 'number' columns

In [45]:
df['street'] = df['street'].fillna('Não registrado')
df['number'] = pd.to_numeric(df['number'], errors='coerce')
df['number'] = df['number'].fillna(0).astype(int)
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,Não registrado,0,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não registrado,0,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,Não registrado,0,NaN
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24,NaN
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738,Conjunto 22

Getting info about 'first_name' and 'additionals'

In [46]:
df[['first_name','additionals']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   first_name   100 non-null    object
 1   additionals  66 non-null     object
dtypes: object(2)
memory usage: 1.7+ KB

Handling NaNs in the 'additionals'

In [47]:
df['additionals'] = df['additionals'].fillna('Sem complemento')
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,Não registrado,0,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534,Sem complemento
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não registrado,0,Sem complemento
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,Não registrado,0,Sem complemento
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24,Sem complemento
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738,Conjunto 22

Showing only 'id', 'first_name', 'last_name' and 'state'

In [49]:
df[['id','first_name','last_name','state']]

    id first_name last_name              state
0    0      Marta     Jesus               Acre
1    1      Luana   Almeida  Rio Grande do Sul
2    2      Frida    Mendes          São Paulo
3    3    Daniela   Avelino        Mato Grosso
4    4    Romário  Teixeira              Bahia
..  ..        ...       ...                ...
95  95    Mariana      Rosa                NaN
96  96      Paulo    Câmara            Sergipe
97  97      Marta      Góes             Paraná
98  98     Cibele     Costa        Mato Grosso
99  99    Jéssica     Jesus             Paraná

[100 rows x 4 columns]