In [7]:
# Importing libraries
import pandas as pd

Reading .xlsx file

In [32]:
df = pd.read_excel("data/Produto.xlsx")
df

    ID                  Name  Price  Id_Category
0    0       Sapato vermelho     96            0
1    1  Bolsa mais que Velha   8000            0
2    2                 Calça     75            0
3    3    Camisa apertadinha    170            0
4    4   Vestido Super curto     57            0
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
7    7       Hidratante caro    800            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2
15  15   O Romance Exagerado     46            3
16  16       Suspense Demais     42            3
17  17  Terror Aterrorizante     45            3
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
20  20               Ai-Fone   1720            4
21  21           Galáxia R10   2007            4
22  22            Chiai-homi   1152            4
23  23                 Ruaei   2795            4
24  24                Nóquia   2663            4
25  25                 Mouse    144            5
26  26               Teclado     53            5
27  27             Pen-Drive    136            5
28  28            Impressora    186            5
29  29            HD Externo    110            5
30  30              Poltrona    110            6
31  31              Almofada    170            6
32  32               Cadeira    164            6
33  33                  Sofá    111            6
34  34                  Mesa    143            6
35  35            Video-Game    602            7
36  36   Máquina Fotográfica    377            7
37  37              Notebook    493            7
38  38                    PC    385            7
39  39     Secador de Cabelo    580            7
40  40              Chuteira    128            8
41  41          Tornozeleira     61            8
42  42               Raquete     97            8
43  43                  Bola    103            8
44  44               Pebolim     82            8
45  45          Futebol 2020     36            9
46  46                  Iôiô     16            9
47  47                  Peão     32            9
48  48             Bey-Blade     55            9
49  49     Casinha de Boneca     39            9

looking for 'Calça' on column 'Name'

In [33]:
df_pants = df.loc[df['Name'] == 'Calça']
df_pants

   ID   Name  Price  Id_Category
2   2  Calça     75            0

Looking for a list of items in the 'Name' column

In [27]:
itens = ['Calça', 'TV','Sapato vermelho', 'Fogão']
df_itens = df.loc[df['Name'].isin(itens)]
df_itens

    ID             Name  Price  Id_Category
0    0  Sapato vermelho     96            0
2    2            Calça     75            0
11  11            Fogão   1373            2
12  12               TV   1992            2

Showing prices that are greater than 1000

In [19]:
df_price_greater_than_1000 = df.loc[df['Price'] > 1000]
df_price_greater_than_1000

    ID                  Name  Price  Id_Category
1    1  Bolsa mais que Velha   8000            0
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2
20  20               Ai-Fone   1720            4
21  21           Galáxia R10   2007            4
22  22            Chiai-homi   1152            4
23  23                 Ruaei   2795            4
24  24                Nóquia   2663            4

Showing prices that are less than 1000

In [21]:
df_price_less_than_1000 = df.loc[df['Price'] < 1000]
df_price_less_than_1000

    ID                  Name  Price  Id_Category
0    0       Sapato vermelho     96            0
2    2                 Calça     75            0
3    3    Camisa apertadinha    170            0
4    4   Vestido Super curto     57            0
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
7    7       Hidratante caro    800            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
15  15   O Romance Exagerado     46            3
16  16       Suspense Demais     42            3
17  17  Terror Aterrorizante     45            3
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
25  25                 Mouse    144            5
26  26               Teclado     53            5
27  27             Pen-Drive    136            5
28  28            Impressora    186            5
29  29            HD Externo    110            5
30  30              Poltrona    110            6
31  31              Almofada    170            6
32  32               Cadeira    164            6
33  33                  Sofá    111            6
34  34                  Mesa    143            6
35  35            Video-Game    602            7
36  36   Máquina Fotográfica    377            7
37  37              Notebook    493            7
38  38                    PC    385            7
39  39     Secador de Cabelo    580            7
40  40              Chuteira    128            8
41  41          Tornozeleira     61            8
42  42               Raquete     97            8
43  43                  Bola    103            8
44  44               Pebolim     82            8
45  45          Futebol 2020     36            9
46  46                  Iôiô     16            9
47  47                  Peão     32            9
48  48             Bey-Blade     55            9
49  49     Casinha de Boneca     39            9

Showing prices between 200 and 1000

In [25]:
df_200_to_1000 = df.loc[(df['Price'] > 200) & (df['Price'] <= 1000)]
df_200_to_1000

    ID                 Name  Price  Id_Category
7    7      Hidratante caro    800            1
35  35           Video-Game    602            7
36  36  Máquina Fotográfica    377            7
37  37             Notebook    493            7
38  38                   PC    385            7
39  39    Secador de Cabelo    580            7

Showing only 'Name', 'Price' from items whose price is between 200 and 1000

In [29]:
df_200_to_1000[['Name','Price']]

                   Name  Price
7       Hidratante caro    800
35           Video-Game    602
36  Máquina Fotográfica    377
37             Notebook    493
38                   PC    385
39    Secador de Cabelo    580